2013/10/16 03:27:02 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1049] Unknown database 'testdrive'' in C:\xampp\htdocs\_AOI\yii\framework\db\CDbConnection.php:382
Stack trace:
#0 C:\xampp\htdocs\_AOI\yii\framework\db\CDbConnection.php(331): CDbConnection->open()
#1 C:\xampp\htdocs\_AOI\yii\framework\db\CDbConnection.php(309): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\_AOI\yii\framework\base\CModule.php(388): CDbConnection->init()
#3 C:\xampp\htdocs\_AOI\yii\framework\base\CModule.php(104): CModule->getComponent('db')
#4 C:\xampp\htdocs\_AOI\yii\framework\gii\generators\crud\CrudCode.php(44): CModule->__get('db')
#5 C:\xampp\htdocs\_AOI\yii\framework\web\CFormModel.php(40): CrudCode->init()
#6 C:\xampp\htdocs\_AOI\yii\framework\gii\CCodeGenerator.php(154): CFormModel->__construct()
#7 C:\xampp\htdocs\_AOI\yii\framework\gii\CCodeGenerator.php(64): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\_AOI\yii\framework\web\actions\CInlineAction.php(50): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\_AOI\yii\framework\web\CController.php(309): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\_AOI\yii\framework\web\CController.php(287): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\_AOI\yii\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\_AOI\yii\framework\web\CWebApplication.php(283): CController->run('')
#13 C:\xampp\htdocs\_AOI\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('gii/crud')
#14 C:\xampp\htdocs\_AOI\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#15 C:\xampp\htdocs\_AOI\yii\framework\yiitest\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/_AOI/yii/framework/yiitest/index.php?r=gii/crud
HTTP_REFERER=http://localhost/_AOI/yii/framework/yiitest/index.php?r=gii/default/index
---
2013/10/16 03:28:11 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1049] Unknown database 'testdrive'' in C:\xampp\htdocs\_AOI\yii\framework\db\CDbConnection.php:382
Stack trace:
#0 C:\xampp\htdocs\_AOI\yii\framework\db\CDbConnection.php(331): CDbConnection->open()
#1 C:\xampp\htdocs\_AOI\yii\framework\db\CDbConnection.php(309): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\_AOI\yii\framework\base\CModule.php(388): CDbConnection->init()
#3 C:\xampp\htdocs\_AOI\yii\framework\base\CModule.php(104): CModule->getComponent('db')
#4 C:\xampp\htdocs\_AOI\yii\framework\gii\generators\model\ModelCode.php(57): CModule->__get('db')
#5 C:\xampp\htdocs\_AOI\yii\framework\web\CFormModel.php(40): ModelCode->init()
#6 C:\xampp\htdocs\_AOI\yii\framework\gii\CCodeGenerator.php(154): CFormModel->__construct()
#7 C:\xampp\htdocs\_AOI\yii\framework\gii\CCodeGenerator.php(64): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\_AOI\yii\framework\web\actions\CInlineAction.php(50): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\_AOI\yii\framework\web\CController.php(309): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\_AOI\yii\framework\web\CController.php(287): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\_AOI\yii\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\_AOI\yii\framework\web\CWebApplication.php(283): CController->run('')
#13 C:\xampp\htdocs\_AOI\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('gii/model')
#14 C:\xampp\htdocs\_AOI\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#15 C:\xampp\htdocs\_AOI\yii\framework\yiitest\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/_AOI/yii/framework/yiitest/index.php?r=gii/model
HTTP_REFERER=http://localhost/_AOI/yii/framework/yiitest/index.php?r=gii/default/index
---
2013/10/16 03:29:52 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1049] Unknown database 'testdrive'' in C:\xampp\htdocs\_AOI\yii\framework\db\CDbConnection.php:382
Stack trace:
#0 C:\xampp\htdocs\_AOI\yii\framework\db\CDbConnection.php(331): CDbConnection->open()
#1 C:\xampp\htdocs\_AOI\yii\framework\db\CDbConnection.php(309): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\_AOI\yii\framework\base\CModule.php(388): CDbConnection->init()
#3 C:\xampp\htdocs\_AOI\yii\framework\base\CModule.php(104): CModule->getComponent('db')
#4 C:\xampp\htdocs\_AOI\yii\framework\gii\generators\model\ModelCode.php(57): CModule->__get('db')
#5 C:\xampp\htdocs\_AOI\yii\framework\web\CFormModel.php(40): ModelCode->init()
#6 C:\xampp\htdocs\_AOI\yii\framework\gii\CCodeGenerator.php(154): CFormModel->__construct()
#7 C:\xampp\htdocs\_AOI\yii\framework\gii\CCodeGenerator.php(64): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\_AOI\yii\framework\web\actions\CInlineAction.php(50): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\_AOI\yii\framework\web\CController.php(309): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\_AOI\yii\framework\web\CController.php(287): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\_AOI\yii\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\_AOI\yii\framework\web\CWebApplication.php(283): CController->run('')
#13 C:\xampp\htdocs\_AOI\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('gii/model')
#14 C:\xampp\htdocs\_AOI\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#15 C:\xampp\htdocs\_AOI\yii\framework\yiitest\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/_AOI/yii/framework/yiitest/index.php?r=gii/model
HTTP_REFERER=http://localhost/_AOI/yii/framework/yiitest/index.php?r=gii/default/index
---
2013/10/16 03:30:29 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1049] Unknown database 'testdrive'' in C:\xampp\htdocs\_AOI\yii\framework\db\CDbConnection.php:382
Stack trace:
#0 C:\xampp\htdocs\_AOI\yii\framework\db\CDbConnection.php(331): CDbConnection->open()
#1 C:\xampp\htdocs\_AOI\yii\framework\db\CDbConnection.php(309): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\_AOI\yii\framework\base\CModule.php(388): CDbConnection->init()
#3 C:\xampp\htdocs\_AOI\yii\framework\base\CModule.php(104): CModule->getComponent('db')
#4 C:\xampp\htdocs\_AOI\yii\framework\gii\generators\model\ModelCode.php(57): CModule->__get('db')
#5 C:\xampp\htdocs\_AOI\yii\framework\web\CFormModel.php(40): ModelCode->init()
#6 C:\xampp\htdocs\_AOI\yii\framework\gii\CCodeGenerator.php(154): CFormModel->__construct()
#7 C:\xampp\htdocs\_AOI\yii\framework\gii\CCodeGenerator.php(64): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\_AOI\yii\framework\web\actions\CInlineAction.php(50): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\_AOI\yii\framework\web\CController.php(309): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\_AOI\yii\framework\web\CController.php(287): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\_AOI\yii\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\_AOI\yii\framework\web\CWebApplication.php(283): CController->run('')
#13 C:\xampp\htdocs\_AOI\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('gii/model')
#14 C:\xampp\htdocs\_AOI\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#15 C:\xampp\htdocs\_AOI\yii\framework\yiitest\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/_AOI/yii/framework/yiitest/index.php?r=gii/model
HTTP_REFERER=http://localhost/_AOI/yii/framework/yiitest/index.php?r=gii/default/index
---
2013/10/16 03:30:51 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1049] Unknown database 'testdrive'' in C:\xampp\htdocs\_AOI\yii\framework\db\CDbConnection.php:382
Stack trace:
#0 C:\xampp\htdocs\_AOI\yii\framework\db\CDbConnection.php(331): CDbConnection->open()
#1 C:\xampp\htdocs\_AOI\yii\framework\db\CDbConnection.php(309): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\_AOI\yii\framework\base\CModule.php(388): CDbConnection->init()
#3 C:\xampp\htdocs\_AOI\yii\framework\base\CModule.php(104): CModule->getComponent('db')
#4 C:\xampp\htdocs\_AOI\yii\framework\gii\generators\crud\CrudCode.php(44): CModule->__get('db')
#5 C:\xampp\htdocs\_AOI\yii\framework\web\CFormModel.php(40): CrudCode->init()
#6 C:\xampp\htdocs\_AOI\yii\framework\gii\CCodeGenerator.php(154): CFormModel->__construct()
#7 C:\xampp\htdocs\_AOI\yii\framework\gii\CCodeGenerator.php(64): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\_AOI\yii\framework\web\actions\CInlineAction.php(50): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\_AOI\yii\framework\web\CController.php(309): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\_AOI\yii\framework\web\CController.php(287): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\_AOI\yii\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\_AOI\yii\framework\web\CWebApplication.php(283): CController->run('')
#13 C:\xampp\htdocs\_AOI\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('gii/crud')
#14 C:\xampp\htdocs\_AOI\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#15 C:\xampp\htdocs\_AOI\yii\framework\yiitest\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/_AOI/yii/framework/yiitest/index.php?r=gii/crud
HTTP_REFERER=http://localhost/_AOI/yii/framework/yiitest/index.php?r=gii/controller
---
2013/10/16 03:49:24 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'testyii.users' doesn't exist. The SQL statement executed was: SHOW COLUMNS FROM `Users`.
2013/10/16 03:50:51 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'testyii.users' doesn't exist. The SQL statement executed was: SHOW COLUMNS FROM `Users`.
2013/10/16 03:52:05 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'testyii.users' doesn't exist. The SQL statement executed was: SHOW COLUMNS FROM `users`.
2013/10/16 03:52:33 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'testyii.users' doesn't exist. The SQL statement executed was: SHOW COLUMNS FROM `users`.
2013/10/16 03:52:41 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'testyii.messages' doesn't exist. The SQL statement executed was: SHOW COLUMNS FROM `messages`.
2013/10/16 03:53:38 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'testyii.messages' doesn't exist. The SQL statement executed was: SHOW COLUMNS FROM `messages`.
2013/10/16 03:58:58 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'testyii.user' doesn't exist. The SQL statement executed was: SHOW COLUMNS FROM `user`.
2013/10/16 04:16:04 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'testyii.tbl_mess' doesn't exist. The SQL statement executed was: SHOW COLUMNS FROM `tbl_mess`.
2013/10/16 04:19:40 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'testyii.gfdgfdg' doesn't exist. The SQL statement executed was: SHOW COLUMNS FROM `gfdgfdg`.
2013/10/16 04:20:16 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'testyii.gfdgfdg' doesn't exist. The SQL statement executed was: SHOW COLUMNS FROM `gfdgfdg`.
2013/10/16 04:20:19 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'testyii.gfdgfdg' doesn't exist. The SQL statement executed was: SHOW COLUMNS FROM `gfdgfdg`.
